# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      uses: robherley/go-test-action@v0.1.0
      with:
           # Directory of go module to test
#            moduleDirectory: handlers
           # Arguments to `go test`, `-json` will be prepended
           testArguments: ./...
           # Omit any packages from summary output that do not have tests
           omitUntestedPackages: false
           # Omit the pie chart from the summary output
           omitPie: false

    - name: Go Coverage
       # You may pin to the exact commit or the version.
       # uses: gwatts/go-coverage-action@cf5795fd4027fa3163339b4c284ab50532e65d11
      uses: gwatts/go-coverage-action@v1.3.0
#       with:
#          working-directory: handlers

    - name: Build Fake Printer
      run: go build -v ./fake-printer/main.go

    - name: Build Halot One Thing
      run: go build -v ./halot-one-thing.go
    
    - name: Build Server CMD
      run: go build -v ./cmd/halot-one/main.go
